"""init

Revision ID: 907a80dc8ab8
Revises: 
Create Date: 2019-06-07 07:27:46.433766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907a80dc8ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_deleted_at'), 'issue', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_issue_updated_at'), 'issue', ['updated_at'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_deleted_at'), 'note', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_note_updated_at'), 'note', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_updated_at'), table_name='note')
    op.drop_index(op.f('ix_note_deleted_at'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_issue_updated_at'), table_name='issue')
    op.drop_index(op.f('ix_issue_deleted_at'), table_name='issue')
    op.drop_table('issue')
    # ### end Alembic commands ###
